flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- aeson-1.0.0.0
- binary-0.7.6.1
- snowflake-0.1.0.0
- time-1.5.0.1
- time-exts-2.1.0
- timezone-olson-0.1.7
- timezone-series-0.1.5.1
resolver: nightly-2016-08-13
